name: sixam_mart_store
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.0.3+6

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  shimmer_animation: ^2.0.0
  image_picker: ^1.1.2
  http: ^0.13.3
  url_launcher: ^6.1.2
  vibration: ^1.7.7
  audioplayers: ^0.20.1
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.0.0
  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
  flutter_html: ^3.0.0-alpha.5
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils: ^1.0.0
  photo_view: ^0.15.0
  image_compression_flutter: ^1.0.2
  win32: ^3.1.4
  google_maps_flutter: ^2.1.1
  geolocator: ^12.0.0
  pin_code_fields: ^8.0.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900